services:
  postgres:
    image: postgres:15
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: fintrackDb
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: